// 一次性工具：把上游包内置的真实浏览器 ClientHello 标本抽取为本地字面量
// （specimens/data.go）。抽取完成后语料数据即本地冻结，不再依赖上游包，
// 上游更新也不会悄悄改变我们的回归基线。
//
// 用法（在 tests/e2e 目录下）：
//
//	go run ./cmd/extract-specimens
package main

import (
	"bytes"
	"fmt"
	"os"

	"github.com/gospider007/ja3"
)

type src struct {
	name     string
	family   string
	version  string
	platform string
	spec     *ja3.GospiderSpec
}

func main() {
	srcs := []src{
		{"chrome_137_macos", "chrome", "137", "macOS", ja3.Chrome_Mac_arm64_137},
		{"chrome_141_macos", "chrome", "141", "macOS", ja3.Chrome_Mac_arm64_141},
		{"chrome_142_macos", "chrome", "142", "macOS", ja3.Chrome_Mac_arm64_142},
		{"chrome_143_macos", "chrome", "143", "macOS", ja3.Chrome_Mac_arm64_143},
		{"chrome_152_macos", "chrome", "152", "macOS", ja3.Chrome_Mac_arm64_152},
		{"edge_141_macos", "edge", "141", "macOS", ja3.Edge_Mac_arm64_141},
		{"firefox_140_macos", "firefox", "140", "macOS", ja3.Firefox_Mac_arm64_140},
		{"firefox_144_macos", "firefox", "144", "macOS", ja3.Firefox_Mac_arm64_144},
		{"safari_18_macos", "safari", "18", "macOS", ja3.Safari_Mac_arm64_18},
		{"safari_26_macos", "safari", "26", "macOS", ja3.Safari_Mac_arm64_26},
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/extract-specimens. DO NOT EDIT.\n")
	buf.WriteString("//\n")
	buf.WriteString("// 真实浏览器 ClientHello 标本：hex 为抓包原始字节（含 5 字节 TLS record 头），\n")
	buf.WriteString("// H2Settings/H2ConnFlow 为同一抓包中的 HTTP/2 帧参数。\n")
	buf.WriteString("// 数据本地冻结，供语料回归与 profile 生成使用。\n\n")
	buf.WriteString("package specimens\n\n")
	buf.WriteString("var all = []Item{\n")
	for _, s := range srcs {
		if s.spec == nil || s.spec.TLSSpec == nil {
			fmt.Fprintf(os.Stderr, "skip %s: nil spec\n", s.name)
			continue
		}
		var settings [][2]uint32
		var connFlow uint32
		if h2 := s.spec.H2Spec; h2 != nil {
			connFlow = h2.ConnFlow
			for _, st := range h2.Settings {
				settings = append(settings, [2]uint32{uint32(st.ID), st.Val})
			}
		}
		fmt.Fprintf(&buf, "\t{Name: %q, Family: %q, Version: %q, Platform: %q,\n", s.name, s.family, s.version, s.platform)
		fmt.Fprintf(&buf, "\t\tHex: %q,\n", s.spec.TLSSpec.Hex())
		fmt.Fprintf(&buf, "\t\tH2Settings: %#v, H2ConnFlow: %d},\n", settings, connFlow)
	}
	buf.WriteString("}\n")

	out := "specimens/data.go"
	if err := os.WriteFile(out, buf.Bytes(), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s (%d bytes)\n", out, buf.Len())
}
